version: '3'
services:
    app:
        build:
            args:
                user: extendeal_challange
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: extendeal_challange_api
        container_name: extendeal_challange_api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
        - ./:/var/www
        networks:
        - extendeal_challange_api
        depends_on:
            - mysql
            - nginx
            - redis
    mysql:
        image: 'arm64v8/mysql:oracle'
        container_name: extendeal_challange_api_db
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - extendeal_challange_api
        volumes:
            - 'extendeal_challange_api_mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    nginx:
        image: nginx:alpine
        container_name: extendeal_challange_api_nginx
        restart: unless-stopped
        ports:
        - 8070:80
        volumes:
        - ./:/var/www
        - ./docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf 
        networks:
        - extendeal_challange_api
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6380}:6380'
        networks:
            - extendeal_challange_api
        volumes:
            - 'extendeal_challange_api_redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    extendeal_challange_api:
        driver: bridge
volumes:
    extendeal_challange_api_mysql:
        driver: local
    extendeal_challange_api_redis:
        driver: local